shifts:
- startDate: Mon 26 Oct 2020
  user: jonsie
- startDate: Mon 02 Nov 2020
  user: mneterval@google.com
- startDate: Mon 09 Nov 2020
  user: plumpy@google.com
- startDate: Mon 16 Nov 2020
  user: robzienert
- startDate: Mon 23 Nov 2020
  user: ajordens
- startDate: Mon 30 Nov 2020
  user: cfieber
- startDate: Mon 07 Dec 2020
  user: claymccoy
- startDate: Mon 14 Dec 2020
  user: ethanfrogers
- startDate: Mon 21 Dec 2020
  stopDate: Sun 27 Dec 2020
  user: ezimanyi
